//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Screen5 : Neo.ApplicationFramework.Controls.Controls.Form, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private System.Windows.Forms.ListView m_ListView;
        
        private System.Windows.Forms.DataGrid m_DataGrid;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnImport;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnImportSetting;
        
        private bool m_Initialized_Screen5;
        
        public Screen5() {
            this.InitializeComponent();
            this.ListView.SelectedIndexChanged += new System.EventHandler(this.ListView_SelectedIndexChanged);
            this.btnImport.Click += new System.EventHandler(this.btnImport_Click);
            this.Adapter.Opened += new System.EventHandler(this.Screen5_Opened);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_btnImportSetting.Click += new System.EventHandler(this.m_btnImportSetting_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected System.Windows.Forms.ListView ListView {
            get {
                return this.m_ListView;
            }
            set {
                this.m_ListView = value;
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnImport {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnImport);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnImportSetting {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnImportSetting);
            }
        }
        
        protected System.Windows.Forms.DataGrid DataGrid {
            get {
                return this.m_DataGrid;
            }
            set {
                this.m_DataGrid = value;
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_ListView = new System.Windows.Forms.ListView();
            this.m_DataGrid = new System.Windows.Forms.DataGrid();
            this.m_btnImport = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnImportSetting = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImport)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImportSetting)).BeginInit();
            this.SuspendLayout();
            // 
            // Screen5
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_ListView
            // 
            this.m_ListView.Enabled = true;
            this.m_ListView.Font = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_ListView.Location = new System.Drawing.Point(8, 10);
            this.m_ListView.Name = "m_ListView_ListView";
            this.m_ListView.Size = new System.Drawing.Size(402, 96);
            this.m_ListView.TabIndex = 0;
            // 
            // m_DataGrid
            // 
            this.m_DataGrid.BackgroundColor = System.Drawing.SystemColors.AppWorkspace;
            this.m_DataGrid.Enabled = true;
            this.m_DataGrid.Font = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_DataGrid.Location = new System.Drawing.Point(8, 112);
            this.m_DataGrid.Name = "m_DataGrid_DataGrid";
            this.m_DataGrid.RowHeadersVisible = false;
            this.m_DataGrid.Size = new System.Drawing.Size(402, 181);
            this.m_DataGrid.TabIndex = 0;
            // 
            // m_btnImport
            // 
            this.m_btnImport.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnImport.BlinkDynamicsValue = false;
            this.m_btnImport.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnImport.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnImport.DelayMouseInputPeriod = 0;
            this.m_btnImport.EnabledDynamicsValue = true;
            this.m_btnImport.FontSizePixels = 7;
            this.m_btnImport.ForceTransparency = true;
            this.m_btnImport.Height = 20;
            this.m_btnImport.IndicatorMargin = null;
            this.m_btnImport.Left = 309;
            this.m_btnImport.Name = "m_btnImport";
            this.m_btnImport.RequiresTransparency = true;
            this.m_btnImport.ScreenOwnerName = "Screen5";
            this.m_btnImport.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnImport.TextHeight = 8;
            this.m_btnImport.TextValue = 0D;
            this.m_btnImport.TextWidth = 38;
            this.m_btnImport.Top = 297;
            this.m_btnImport.Value = 0D;
            this.m_btnImport.VisibleDynamicsValue = true;
            this.m_btnImport.VisualPropertiesHashCode = -2147398860;
            this.m_btnImport.Width = 48;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.DelayMouseInputPeriod = 0;
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontSizePixels = 7;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 20;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 362;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "Screen5";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 8;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 38;
            this.m_Button1.Top = 297;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -2147398860;
            this.m_Button1.Width = 48;
            // 
            // m_btnImportSetting
            // 
            this.m_btnImportSetting.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnImportSetting.BlinkDynamicsValue = false;
            this.m_btnImportSetting.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnImportSetting.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnImportSetting.DelayMouseInputPeriod = 0;
            this.m_btnImportSetting.EnabledDynamicsValue = true;
            this.m_btnImportSetting.FontSizePixels = 7;
            this.m_btnImportSetting.ForceTransparency = true;
            this.m_btnImportSetting.Height = 20;
            this.m_btnImportSetting.IndicatorMargin = null;
            this.m_btnImportSetting.Left = 174;
            this.m_btnImportSetting.Name = "m_btnImportSetting";
            this.m_btnImportSetting.RequiresTransparency = true;
            this.m_btnImportSetting.ScreenOwnerName = "Screen5";
            this.m_btnImportSetting.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_btnImportSetting.TextHeight = 8;
            this.m_btnImportSetting.TextValue = 0D;
            this.m_btnImportSetting.TextWidth = 121;
            this.m_btnImportSetting.Top = 297;
            this.m_btnImportSetting.Value = 0D;
            this.m_btnImportSetting.VisibleDynamicsValue = true;
            this.m_btnImportSetting.VisualPropertiesHashCode = 2090076744;
            this.m_btnImportSetting.Width = 131;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.ClientSize = new System.Drawing.Size(418, 320);
            this.IsCacheable = false;
            this.Location = new System.Drawing.Point(102, 56);
            this.ModalScreen = true;
            this.Name = "Screen5";
            this.PopupScreen = true;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "Default";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Screen5 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Screen5) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_DataGrid);
            this.Controls.Add(this.m_ListView);
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_btnImport);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_btnImportSetting);
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImport)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImportSetting)).EndInit();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            this.LogClose("m_Button1", "Click", "Close Screen", "");
            this.Close();
        }
        
        private void m_btnImportSetting_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnImportSetting", "Click", "Show Screen", "Screen6", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Screen6.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen5));
            this.m_btnImport.Text = resources.GetText("Screen5.btnImport.Text", "Import");
            this.m_Button1.Text = resources.GetText("Screen5.Button1.Text", "Close");
            this.m_btnImportSetting.Text = resources.GetText("Screen5.btnImportSetting.Text", "Import CSV File Column Name Setting");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Screen5) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
