//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Screen1 : Screen2, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage {
        
        private System.Windows.Forms.DateTimePicker m_queryStartDate;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbEndHour;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbStartHour;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbEndMinute;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbStartMinute;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbStartSecond;
        
        private Neo.ApplicationFramework.Controls.Controls.ComboBox m_cbbEndSecond;
        
        private System.Windows.Forms.DateTimePicker m_queryEndDate;
        
        private System.Windows.Forms.DataGrid m_DataGrid;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnQuery;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnStartlog;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnStopLog;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnLogOnce;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnQueryWithTime;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnImport;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnExport;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnSetting;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnExportSetting;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_btnHistory;
        
        private bool m_Initialized_Screen1;
        
        public Screen1() {
            this.InitializeComponent();
            this.btnQuery.Click += new System.EventHandler(this.btnQuery_Click);
            this.btnStartlog.Click += new System.EventHandler(this.btnStartlog_Click);
            this.btnStopLog.Click += new System.EventHandler(this.btnStopLog_Click);
            this.btnLogOnce.Click += new System.EventHandler(this.btnLogOnce_Click);
            this.btnQueryWithTime.Click += new System.EventHandler(this.btnQueryWithTime_Click);
            this.btnExport.Click += new System.EventHandler(this.btnExport_Click);
            this.btnHistory.Click += new System.EventHandler(this.btnHistory_Click);
            this.Adapter.Opened += new System.EventHandler(this.Screen1_Opened);
            this.m_btnImport.Click += new System.EventHandler(this.m_btnImport_Action_Click);
            this.m_btnSetting.Click += new System.EventHandler(this.m_btnSetting_Action_Click);
            this.m_btnExportSetting.Click += new System.EventHandler(this.m_btnExportSetting_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnQuery {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnQuery);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnStartlog {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnStartlog);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnStopLog {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnStopLog);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnLogOnce {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnLogOnce);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnQueryWithTime {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnQueryWithTime);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnImport {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnImport);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnExport {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnExport);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnSetting {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnSetting);
            }
        }
        
        protected System.Windows.Forms.DateTimePicker queryStartDate {
            get {
                return this.m_queryStartDate;
            }
            set {
                this.m_queryStartDate = value;
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbEndHour {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbEndHour);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbStartHour {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbStartHour);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbEndMinute {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbEndMinute);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbStartMinute {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbStartMinute);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbStartSecond {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbStartSecond);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter cbbEndSecond {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ComboBoxCFAdapter>(this.m_cbbEndSecond);
            }
        }
        
        protected System.Windows.Forms.DateTimePicker queryEndDate {
            get {
                return this.m_queryEndDate;
            }
            set {
                this.m_queryEndDate = value;
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnExportSetting {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnExportSetting);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter btnHistory {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_btnHistory);
            }
        }
        
        protected System.Windows.Forms.DataGrid DataGrid {
            get {
                return this.m_DataGrid;
            }
            set {
                this.m_DataGrid = value;
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_queryStartDate = new System.Windows.Forms.DateTimePicker();
            this.m_cbbEndHour = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_cbbStartHour = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_cbbEndMinute = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_cbbStartMinute = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_cbbStartSecond = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_cbbEndSecond = new Neo.ApplicationFramework.Controls.Controls.ComboBox();
            this.m_queryEndDate = new System.Windows.Forms.DateTimePicker();
            this.m_DataGrid = new System.Windows.Forms.DataGrid();
            this.m_btnQuery = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnStartlog = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnStopLog = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnLogOnce = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnQueryWithTime = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnImport = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnExport = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnSetting = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_btnExportSetting = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_btnHistory = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndHour)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartHour)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndMinute)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartMinute)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartSecond)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndSecond)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnQuery)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnStartlog)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnStopLog)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLogOnce)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnQueryWithTime)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImport)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnExport)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnSetting)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnExportSetting)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnHistory)).BeginInit();
            this.SuspendLayout();
            // 
            // Screen1
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_queryStartDate
            // 
            this.m_queryStartDate.CalendarFont = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_queryStartDate.Enabled = true;
            this.m_queryStartDate.Font = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_queryStartDate.Location = new System.Drawing.Point(56, 43);
            this.m_queryStartDate.Name = "m_queryStartDate_DateTimePicker";
            this.m_queryStartDate.Size = new System.Drawing.Size(120, 22);
            this.m_queryStartDate.TabIndex = 0;
            this.m_queryStartDate.Value = new System.DateTime(2019, 4, 15, 14, 47, 38, 549);
            // 
            // m_cbbEndHour
            // 
            this.m_cbbEndHour.EnabledDynamicsValue = true;
            this.m_cbbEndHour.FontFamily = "Tahoma";
            this.m_cbbEndHour.FontSizePixels = 12;
            this.m_cbbEndHour.ForeColor = System.Drawing.Color.Black;
            this.m_cbbEndHour.Location = new System.Drawing.Point(184, 65);
            this.m_cbbEndHour.Name = "m_cbbEndHour";
            this.m_cbbEndHour.Size = new System.Drawing.Size(40, 20);
            this.m_cbbEndHour.TabIndex = 2147483647;
            this.m_cbbEndHour.VisibleDynamicsValue = true;
            // 
            // m_cbbStartHour
            // 
            this.m_cbbStartHour.EnabledDynamicsValue = true;
            this.m_cbbStartHour.FontFamily = "Tahoma";
            this.m_cbbStartHour.FontSizePixels = 12;
            this.m_cbbStartHour.ForeColor = System.Drawing.Color.Black;
            this.m_cbbStartHour.Location = new System.Drawing.Point(184, 43);
            this.m_cbbStartHour.Name = "m_cbbStartHour";
            this.m_cbbStartHour.Size = new System.Drawing.Size(40, 20);
            this.m_cbbStartHour.TabIndex = 2147483647;
            this.m_cbbStartHour.VisibleDynamicsValue = true;
            // 
            // m_cbbEndMinute
            // 
            this.m_cbbEndMinute.EnabledDynamicsValue = true;
            this.m_cbbEndMinute.FontFamily = "Tahoma";
            this.m_cbbEndMinute.FontSizePixels = 12;
            this.m_cbbEndMinute.ForeColor = System.Drawing.Color.Black;
            this.m_cbbEndMinute.Location = new System.Drawing.Point(229, 65);
            this.m_cbbEndMinute.Name = "m_cbbEndMinute";
            this.m_cbbEndMinute.Size = new System.Drawing.Size(40, 20);
            this.m_cbbEndMinute.TabIndex = 2147483647;
            this.m_cbbEndMinute.VisibleDynamicsValue = true;
            // 
            // m_cbbStartMinute
            // 
            this.m_cbbStartMinute.EnabledDynamicsValue = true;
            this.m_cbbStartMinute.FontFamily = "Tahoma";
            this.m_cbbStartMinute.FontSizePixels = 12;
            this.m_cbbStartMinute.ForeColor = System.Drawing.Color.Black;
            this.m_cbbStartMinute.Location = new System.Drawing.Point(229, 43);
            this.m_cbbStartMinute.Name = "m_cbbStartMinute";
            this.m_cbbStartMinute.Size = new System.Drawing.Size(40, 20);
            this.m_cbbStartMinute.TabIndex = 2147483647;
            this.m_cbbStartMinute.VisibleDynamicsValue = true;
            // 
            // m_cbbStartSecond
            // 
            this.m_cbbStartSecond.EnabledDynamicsValue = true;
            this.m_cbbStartSecond.FontFamily = "Tahoma";
            this.m_cbbStartSecond.FontSizePixels = 12;
            this.m_cbbStartSecond.ForeColor = System.Drawing.Color.Black;
            this.m_cbbStartSecond.Location = new System.Drawing.Point(274, 43);
            this.m_cbbStartSecond.Name = "m_cbbStartSecond";
            this.m_cbbStartSecond.Size = new System.Drawing.Size(40, 20);
            this.m_cbbStartSecond.TabIndex = 2147483647;
            this.m_cbbStartSecond.VisibleDynamicsValue = true;
            // 
            // m_cbbEndSecond
            // 
            this.m_cbbEndSecond.EnabledDynamicsValue = true;
            this.m_cbbEndSecond.FontFamily = "Tahoma";
            this.m_cbbEndSecond.FontSizePixels = 12;
            this.m_cbbEndSecond.ForeColor = System.Drawing.Color.Black;
            this.m_cbbEndSecond.Location = new System.Drawing.Point(274, 65);
            this.m_cbbEndSecond.Name = "m_cbbEndSecond";
            this.m_cbbEndSecond.Size = new System.Drawing.Size(40, 20);
            this.m_cbbEndSecond.TabIndex = 2147483647;
            this.m_cbbEndSecond.VisibleDynamicsValue = true;
            // 
            // m_queryEndDate
            // 
            this.m_queryEndDate.CalendarFont = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_queryEndDate.Enabled = true;
            this.m_queryEndDate.Font = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_queryEndDate.Location = new System.Drawing.Point(56, 62);
            this.m_queryEndDate.Name = "m_queryEndDate_DateTimePicker";
            this.m_queryEndDate.Size = new System.Drawing.Size(120, 22);
            this.m_queryEndDate.TabIndex = 0;
            this.m_queryEndDate.Value = new System.DateTime(2019, 4, 15, 14, 47, 38, 556);
            // 
            // m_DataGrid
            // 
            this.m_DataGrid.BackgroundColor = System.Drawing.SystemColors.AppWorkspace;
            this.m_DataGrid.Enabled = true;
            this.m_DataGrid.Font = new System.Drawing.Font("新細明體", 9F, System.Drawing.FontStyle.Regular);
            this.m_DataGrid.Location = new System.Drawing.Point(325, 17);
            this.m_DataGrid.Name = "m_DataGrid_DataGrid";
            this.m_DataGrid.RowHeadersVisible = false;
            this.m_DataGrid.Size = new System.Drawing.Size(454, 450);
            this.m_DataGrid.TabIndex = 0;
            // 
            // m_btnQuery
            // 
            this.m_btnQuery.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnQuery.BlinkDynamicsValue = false;
            this.m_btnQuery.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnQuery.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnQuery.DelayMouseInputPeriod = 0;
            this.m_btnQuery.EnabledDynamicsValue = true;
            this.m_btnQuery.FontSizePixels = 10;
            this.m_btnQuery.ForceTransparency = true;
            this.m_btnQuery.Height = 22;
            this.m_btnQuery.IndicatorMargin = null;
            this.m_btnQuery.Left = 29;
            this.m_btnQuery.Name = "m_btnQuery";
            this.m_btnQuery.RequiresTransparency = true;
            this.m_btnQuery.ScreenOwnerName = "Screen1";
            this.m_btnQuery.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_btnQuery.TextHeight = 12;
            this.m_btnQuery.TextValue = 0D;
            this.m_btnQuery.TextWidth = 72;
            this.m_btnQuery.Top = 89;
            this.m_btnQuery.Value = 0D;
            this.m_btnQuery.VisibleDynamicsValue = true;
            this.m_btnQuery.VisualPropertiesHashCode = 596513698;
            this.m_btnQuery.Width = 82;
            // 
            // m_btnStartlog
            // 
            this.m_btnStartlog.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnStartlog.BlinkDynamicsValue = false;
            this.m_btnStartlog.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnStartlog.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnStartlog.DelayMouseInputPeriod = 0;
            this.m_btnStartlog.EnabledDynamicsValue = true;
            this.m_btnStartlog.FontSizePixels = 10;
            this.m_btnStartlog.ForceTransparency = true;
            this.m_btnStartlog.Height = 22;
            this.m_btnStartlog.IndicatorMargin = null;
            this.m_btnStartlog.Left = 30;
            this.m_btnStartlog.Name = "m_btnStartlog";
            this.m_btnStartlog.RequiresTransparency = true;
            this.m_btnStartlog.ScreenOwnerName = "Screen1";
            this.m_btnStartlog.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_btnStartlog.TextHeight = 12;
            this.m_btnStartlog.TextValue = 0D;
            this.m_btnStartlog.TextWidth = 72;
            this.m_btnStartlog.Top = 17;
            this.m_btnStartlog.Value = 0D;
            this.m_btnStartlog.VisibleDynamicsValue = true;
            this.m_btnStartlog.VisualPropertiesHashCode = 596513698;
            this.m_btnStartlog.Width = 82;
            // 
            // m_btnStopLog
            // 
            this.m_btnStopLog.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnStopLog.BlinkDynamicsValue = false;
            this.m_btnStopLog.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnStopLog.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnStopLog.DelayMouseInputPeriod = 0;
            this.m_btnStopLog.EnabledDynamicsValue = true;
            this.m_btnStopLog.FontSizePixels = 10;
            this.m_btnStopLog.ForceTransparency = true;
            this.m_btnStopLog.Height = 22;
            this.m_btnStopLog.IndicatorMargin = null;
            this.m_btnStopLog.Left = 133;
            this.m_btnStopLog.Name = "m_btnStopLog";
            this.m_btnStopLog.RequiresTransparency = true;
            this.m_btnStopLog.ScreenOwnerName = "Screen1";
            this.m_btnStopLog.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_btnStopLog.TextHeight = 12;
            this.m_btnStopLog.TextValue = 0D;
            this.m_btnStopLog.TextWidth = 72;
            this.m_btnStopLog.Top = 17;
            this.m_btnStopLog.Value = 0D;
            this.m_btnStopLog.VisibleDynamicsValue = true;
            this.m_btnStopLog.VisualPropertiesHashCode = 596513698;
            this.m_btnStopLog.Width = 82;
            // 
            // m_btnLogOnce
            // 
            this.m_btnLogOnce.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnLogOnce.BlinkDynamicsValue = false;
            this.m_btnLogOnce.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnLogOnce.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnLogOnce.DelayMouseInputPeriod = 0;
            this.m_btnLogOnce.EnabledDynamicsValue = true;
            this.m_btnLogOnce.FontSizePixels = 10;
            this.m_btnLogOnce.ForceTransparency = true;
            this.m_btnLogOnce.Height = 22;
            this.m_btnLogOnce.IndicatorMargin = null;
            this.m_btnLogOnce.Left = 232;
            this.m_btnLogOnce.Name = "m_btnLogOnce";
            this.m_btnLogOnce.RequiresTransparency = true;
            this.m_btnLogOnce.ScreenOwnerName = "Screen1";
            this.m_btnLogOnce.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_btnLogOnce.TextHeight = 12;
            this.m_btnLogOnce.TextValue = 0D;
            this.m_btnLogOnce.TextWidth = 72;
            this.m_btnLogOnce.Top = 17;
            this.m_btnLogOnce.Value = 0D;
            this.m_btnLogOnce.VisibleDynamicsValue = true;
            this.m_btnLogOnce.VisualPropertiesHashCode = 596513698;
            this.m_btnLogOnce.Width = 82;
            // 
            // m_btnQueryWithTime
            // 
            this.m_btnQueryWithTime.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnQueryWithTime.BlinkDynamicsValue = false;
            this.m_btnQueryWithTime.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnQueryWithTime.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnQueryWithTime.DelayMouseInputPeriod = 0;
            this.m_btnQueryWithTime.EnabledDynamicsValue = true;
            this.m_btnQueryWithTime.FontSizePixels = 10;
            this.m_btnQueryWithTime.ForceTransparency = true;
            this.m_btnQueryWithTime.Height = 22;
            this.m_btnQueryWithTime.IndicatorMargin = null;
            this.m_btnQueryWithTime.Left = 128;
            this.m_btnQueryWithTime.Name = "m_btnQueryWithTime";
            this.m_btnQueryWithTime.RequiresTransparency = true;
            this.m_btnQueryWithTime.ScreenOwnerName = "Screen1";
            this.m_btnQueryWithTime.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_btnQueryWithTime.TextHeight = 12;
            this.m_btnQueryWithTime.TextValue = 0D;
            this.m_btnQueryWithTime.TextWidth = 77;
            this.m_btnQueryWithTime.Top = 89;
            this.m_btnQueryWithTime.Value = 0D;
            this.m_btnQueryWithTime.VisibleDynamicsValue = true;
            this.m_btnQueryWithTime.VisualPropertiesHashCode = -941738599;
            this.m_btnQueryWithTime.Width = 87;
            this.m_btnQueryWithTime.WordWrap = true;
            // 
            // m_btnImport
            // 
            this.m_btnImport.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnImport.BlinkDynamicsValue = false;
            this.m_btnImport.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnImport.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnImport.DelayMouseInputPeriod = 0;
            this.m_btnImport.EnabledDynamicsValue = true;
            this.m_btnImport.FontSizePixels = 10;
            this.m_btnImport.ForceTransparency = true;
            this.m_btnImport.Height = 22;
            this.m_btnImport.IndicatorMargin = null;
            this.m_btnImport.Left = 29;
            this.m_btnImport.Name = "m_btnImport";
            this.m_btnImport.RequiresTransparency = true;
            this.m_btnImport.ScreenOwnerName = "Screen1";
            this.m_btnImport.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_btnImport.TextHeight = 12;
            this.m_btnImport.TextValue = 0D;
            this.m_btnImport.TextWidth = 275;
            this.m_btnImport.Top = 141;
            this.m_btnImport.Value = 0D;
            this.m_btnImport.VisibleDynamicsValue = true;
            this.m_btnImport.VisualPropertiesHashCode = 320932196;
            this.m_btnImport.Width = 285;
            // 
            // m_btnExport
            // 
            this.m_btnExport.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnExport.BlinkDynamicsValue = false;
            this.m_btnExport.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnExport.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnExport.DelayMouseInputPeriod = 0;
            this.m_btnExport.EnabledDynamicsValue = true;
            this.m_btnExport.FontSizePixels = 10;
            this.m_btnExport.ForceTransparency = true;
            this.m_btnExport.Height = 22;
            this.m_btnExport.IndicatorMargin = null;
            this.m_btnExport.Left = 184;
            this.m_btnExport.Name = "m_btnExport";
            this.m_btnExport.RequiresTransparency = true;
            this.m_btnExport.ScreenOwnerName = "Screen1";
            this.m_btnExport.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_btnExport.TextHeight = 12;
            this.m_btnExport.TextValue = 0D;
            this.m_btnExport.TextWidth = 120;
            this.m_btnExport.Top = 115;
            this.m_btnExport.Value = 0D;
            this.m_btnExport.VisibleDynamicsValue = true;
            this.m_btnExport.VisualPropertiesHashCode = 1683968042;
            this.m_btnExport.Width = 130;
            // 
            // m_btnSetting
            // 
            this.m_btnSetting.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnSetting.BlinkDynamicsValue = false;
            this.m_btnSetting.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnSetting.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnSetting.DelayMouseInputPeriod = 0;
            this.m_btnSetting.EnabledDynamicsValue = true;
            this.m_btnSetting.FontSizePixels = 10;
            this.m_btnSetting.ForceTransparency = true;
            this.m_btnSetting.Height = 22;
            this.m_btnSetting.IndicatorMargin = null;
            this.m_btnSetting.Left = 29;
            this.m_btnSetting.Name = "m_btnSetting";
            this.m_btnSetting.RequiresTransparency = true;
            this.m_btnSetting.ScreenOwnerName = "Screen1";
            this.m_btnSetting.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_btnSetting.TextHeight = 12;
            this.m_btnSetting.TextValue = 0D;
            this.m_btnSetting.TextWidth = 275;
            this.m_btnSetting.Top = 166;
            this.m_btnSetting.Value = 0D;
            this.m_btnSetting.VisibleDynamicsValue = true;
            this.m_btnSetting.VisualPropertiesHashCode = 320932196;
            this.m_btnSetting.Width = 285;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.DelayMouseInputPeriod = 0;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 8;
            this.m_Text.Height = 21;
            this.m_Text.Left = 28;
            this.m_Text.Name = "m_Text";
            this.m_Text.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 0D, 2D, 1D);
            this.m_Text.ScreenOwnerName = "Screen1";
            this.m_Text.Top = 41;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 32;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.DelayMouseInputPeriod = 0;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 8;
            this.m_Text1.Height = 21;
            this.m_Text1.Left = 38;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.Padding = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 0D, 2D, 1D);
            this.m_Text1.ScreenOwnerName = "Screen1";
            this.m_Text1.Top = 60;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 19;
            // 
            // m_btnExportSetting
            // 
            this.m_btnExportSetting.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnExportSetting.BlinkDynamicsValue = false;
            this.m_btnExportSetting.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnExportSetting.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnExportSetting.DelayMouseInputPeriod = 0;
            this.m_btnExportSetting.EnabledDynamicsValue = true;
            this.m_btnExportSetting.FontSizePixels = 10;
            this.m_btnExportSetting.ForceTransparency = true;
            this.m_btnExportSetting.Height = 22;
            this.m_btnExportSetting.IndicatorMargin = null;
            this.m_btnExportSetting.Left = 29;
            this.m_btnExportSetting.Name = "m_btnExportSetting";
            this.m_btnExportSetting.RequiresTransparency = true;
            this.m_btnExportSetting.ScreenOwnerName = "Screen1";
            this.m_btnExportSetting.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_btnExportSetting.TextHeight = 12;
            this.m_btnExportSetting.TextValue = 0D;
            this.m_btnExportSetting.TextWidth = 127;
            this.m_btnExportSetting.Top = 115;
            this.m_btnExportSetting.Value = 0D;
            this.m_btnExportSetting.VisibleDynamicsValue = true;
            this.m_btnExportSetting.VisualPropertiesHashCode = 878087598;
            this.m_btnExportSetting.Width = 137;
            // 
            // m_btnHistory
            // 
            this.m_btnHistory.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_btnHistory.BlinkDynamicsValue = false;
            this.m_btnHistory.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_btnHistory.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_btnHistory.DelayMouseInputPeriod = 0;
            this.m_btnHistory.EnabledDynamicsValue = true;
            this.m_btnHistory.FontSizePixels = 10;
            this.m_btnHistory.ForceTransparency = true;
            this.m_btnHistory.Height = 22;
            this.m_btnHistory.IndicatorMargin = null;
            this.m_btnHistory.Left = 232;
            this.m_btnHistory.Name = "m_btnHistory";
            this.m_btnHistory.RequiresTransparency = true;
            this.m_btnHistory.ScreenOwnerName = "Screen1";
            this.m_btnHistory.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_btnHistory.TextHeight = 12;
            this.m_btnHistory.TextValue = 0D;
            this.m_btnHistory.TextWidth = 72;
            this.m_btnHistory.Top = 89;
            this.m_btnHistory.Value = 0D;
            this.m_btnHistory.VisibleDynamicsValue = true;
            this.m_btnHistory.VisualPropertiesHashCode = 596513698;
            this.m_btnHistory.Width = 82;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Screen1";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Screen1 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Screen1) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            this.Controls.Add(this.m_DataGrid);
            this.Controls.Add(this.m_queryEndDate);
            this.Controls.Add(this.m_cbbEndSecond);
            this.Controls.Add(this.m_cbbStartSecond);
            this.Controls.Add(this.m_cbbStartMinute);
            this.Controls.Add(this.m_cbbEndMinute);
            this.Controls.Add(this.m_cbbStartHour);
            this.Controls.Add(this.m_cbbEndHour);
            this.Controls.Add(this.m_queryStartDate);
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndHour)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartHour)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndMinute)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartMinute)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbStartSecond)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_cbbEndSecond)).EndInit();
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_btnQuery);
            this.DrawingPrimitives.Add(this.m_btnStartlog);
            this.DrawingPrimitives.Add(this.m_btnStopLog);
            this.DrawingPrimitives.Add(this.m_btnLogOnce);
            this.DrawingPrimitives.Add(this.m_btnQueryWithTime);
            this.DrawingPrimitives.Add(this.m_btnImport);
            this.DrawingPrimitives.Add(this.m_btnExport);
            this.DrawingPrimitives.Add(this.m_btnSetting);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_btnExportSetting);
            this.DrawingPrimitives.Add(this.m_btnHistory);
            ((System.ComponentModel.ISupportInitialize)(this.m_btnQuery)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnStartlog)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnStopLog)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnLogOnce)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnQueryWithTime)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnImport)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnExport)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnSetting)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnExportSetting)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_btnHistory)).EndInit();
        }
        
        private void m_btnImport_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnImport", "Click", "Show Screen", "Screen5", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Screen5.Show();
        }
        
        private void m_btnSetting_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnSetting", "Click", "Show Screen", "Screen4", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Screen4.Show();
        }
        
        private void m_btnExportSetting_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnExportSetting", "Click", "Show Screen", "Screen3", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.Screen3.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen1));
            this.m_btnQuery.Text = resources.GetText("Screen1.btnQuery.Text", "QueryAll");
            this.m_btnStartlog.Text = resources.GetText("Screen1.btnStartlog.Text", "Start Log");
            this.m_btnStopLog.Text = resources.GetText("Screen1.btnStopLog.Text", "Stop Log");
            this.m_btnLogOnce.Text = resources.GetText("Screen1.btnLogOnce.Text", "Log Once");
            this.m_btnQueryWithTime.Text = resources.GetText("Screen1.btnQueryWithTime.Text", "Query with Time");
            this.m_btnImport.Text = resources.GetText("Screen1.btnImport.Text", "Import DataLogger");
            this.m_btnExport.Text = resources.GetText("Screen1.btnExport.Text", "Export DataLogger");
            this.m_btnSetting.Text = resources.GetText("Screen1.btnSetting.Text", "DataLogger Column Name Setting");
            this.m_Text.Text = resources.GetText("Screen1.Text.Text", "From");
            this.m_Text1.Text = resources.GetText("Screen1.Text1.Text", "To");
            this.m_btnExportSetting.Text = resources.GetText("Screen1.btnExportSetting.Text", "Export Setting");
            this.m_btnHistory.Text = resources.GetText("Screen1.btnHistory.Text", "History Data");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage() {
            this.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Screen1) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
