//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class DataLogger1 : Neo.ApplicationFramework.Tools.DataLogger.DataLogger, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.DataLogger.LogItem m_LogItem1;
		
		private Neo.ApplicationFramework.Tools.DataLogger.LogItem m_LogItem2;
		
		public DataLogger1()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.DataLogger.LogItem LogItem1
		{
			get
			{
				return this.m_LogItem1;
			}
			set
			{
				this.m_LogItem1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.DataLogger.LogItem LogItem2
		{
			get
			{
				return this.m_LogItem2;
			}
			set
			{
				this.m_LogItem2 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			// 
			// DataLogger1
			// 
			this.Guid = new System.Guid("6bc31d84-fc1c-4c18-9800-6b411de277d5");
			this.LogInterval = System.TimeSpan.Parse("00:00:01");
			// 
			// LogItem1
			// 
			this.LogItem1.DatabaseFieldName = "LogItem1";
			this.LogItem1.DataSourceValue = null;
			this.LogItem1.Name = "LogItem1";
			// 
			// LogItem2
			// 
			this.LogItem2.DatabaseFieldName = "LogItem2";
			this.LogItem2.DataSourceValue = null;
			this.LogItem2.Name = "LogItem2";
			this.LogItems.Add(this.LogItem1);
			this.LogItems.Add(this.LogItem2);
			this.LogTrigger = Neo.ApplicationFramework.Interfaces.LogTriggerType.LogDataOnTimerEvent;
			this.SchemaVersion = ((long)(8));
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
			this.LogItem1.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("DataSourceValue", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Tag1"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
			this.LogItem2.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("DataSourceValue", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.Tag2"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
		}
		
		private void InitializeObjectCreations()
		{
			this.LogItem1 = new Neo.ApplicationFramework.Tools.DataLogger.LogItem();
			this.LogItem2 = new Neo.ApplicationFramework.Tools.DataLogger.LogItem();
		}
		
		private void InitializeBeginInits()
		{
		}
		
		private void InitializeEndInits()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(DataLogger1));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
