//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class Screen3 : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Screen3()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.Adapter.Opened += new System.EventHandler(this.Screen3_Opened);
			this.rbtExportOption1.Click += new System.EventHandler(this.rbtExportOption1_Click);
			this.rbtExportOption2.Click += new System.EventHandler(this.rbtExportOption2_Click);
			this.rbtExportOption3.Click += new System.EventHandler(this.rbtExportOption3_Click);
			this.cbExportFilesName.Click += new System.EventHandler(this.cbExportFilesName_Click);
			this.ApplyLanguageInternal();
		}
		
		protected Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter AnalogNumericExportPath
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter>(this.m_AnalogNumericExportPath);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter rbtExportOption1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter>(this.m_rbtExportOption1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter rbtExportOption2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter>(this.m_rbtExportOption2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter rbtExportOption3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter>(this.m_rbtExportOption3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter AnalogNumericFileName
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter>(this.m_AnalogNumericFileName);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter cbExportFilesName
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ToggleButtonAdapter>(this.m_cbExportFilesName);
			}
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen3));
			this.m_rbtExportOption1.Text = resources.GetText("Screen3.rbtExportOption1.Text", "Export to Project Files Folder");
			this.m_rbtExportOption2.Text = resources.GetText("Screen3.rbtExportOption2.Text", "Browse and select an export path");
			this.m_rbtExportOption3.Text = resources.GetText("Screen3.rbtExportOption3.Text", "Export to path :");
			this.m_cbExportFilesName.Text = resources.GetText("Screen3.cbExportFilesName.Text", "Name of exported file");
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
	}
}
