//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class Screen5 : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Screen5()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.Adapter.Opened += new System.EventHandler(this.Screen5_Opened);
			this.ListView.SelectedIndexChanged += new System.EventHandler(this.ListView_SelectedIndexChanged);
			this.btnImport.Click += new System.EventHandler(this.btnImport_Click);
			this.m_Button1.Click += new System.Windows.RoutedEventHandler(this.m_Button1_Action_Click);
			this.m_btnImportSetting.Click += new System.Windows.RoutedEventHandler(this.m_btnImportSetting_Action_Click);
			this.ApplyLanguageInternal();
		}
		
		public System.Windows.Forms.ListView ListView
		{
			get
			{
				return ((System.Windows.Forms.ListView)(this.m_ListView.Control));
			}
		}
		
		public System.Windows.Forms.DataGrid DataGrid
		{
			get
			{
				return ((System.Windows.Forms.DataGrid)(this.m_DataGrid.Control));
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter btnImport
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_btnImport);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter btnImportSetting
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_btnImportSetting);
			}
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		private void m_Button1_Action_Click(object sender, System.EventArgs e)
		{
			this.LogClose("m_Button1", "Click", "Close Screen", "");
			this.Close();
		}
		
		private void m_btnImportSetting_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_btnImportSetting", "Click", "Show Screen", "Screen6", "Default", "");
			Neo.ApplicationFramework.Generated.Globals.Screen6.Show();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen5));
			this.m_btnImport.Text = resources.GetText("Screen5.btnImport.Text", "Import");
			this.m_Button1.Text = resources.GetText("Screen5.Button1.Text", "Close");
			this.m_btnImportSetting.Text = resources.GetText("Screen5.btnImportSetting.Text", "Import CSV File Column Name Setting");
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
	}
}
